apiVersion: forklift.konveyor.io/v1beta1
kind: Toehold
metadata:
  name: nbdkit-toehold
  namespace: openshift-mtv
spec:
  provider:
    name: vcenter
    namespace: openshift-mtv
  bootcImage: quay.io/mnecas0/nbdkit-appliance-bootc:poc
  templateName: nbdkit-toehold
  vmName: nbdkit-toehold-01
  datastore: datastore1
  folder: /Datacenter/vm
  network: "VM Network"
  registrySecret:
    name: nbdkit-appliance-quay
  powerOn: true
  forceRebuild: false
  nbd:
    basePort: 10809
    threads: 8
    sshUser: root
  disks:
    - name: disk0
      sourceVM: bench-vm
      vmdkPath: "[datastore1] bench-vm/bench-vm-000001.vmdk"
      diskMode: independent_nonpersistent
